ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # Print diagnostics
    print_diagnostics: true

    # Wheel odometry configuration
    odom0: /wheel/odom
    odom0_config: [true, true, false,   # x, y position (use these)
                   false, false, true,  # roll, pitch, yaw (only yaw)
                   true, true, false,   # vx, vy (use these)
                   false, false, true,  # angular velocities (only vz)
                   false, false, false] # acceleration (don't use)
    odom0_differential: false
    odom0_relative: false
    # Reduced covariance for more trust in wheel odometry
    odom0_pose_covariance_override: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                                     0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
                                     0.0, 0.0, 0.0, 0.0, 0.0, 0.3]  # Trust wheel yaw moderately
    odom0_twist_covariance_override: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                                      0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                                      0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
                                      0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
                                      0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
                                      0.0, 0.0, 0.0, 0.0, 0.0, 0.1]  # Trust wheel angular velocity

    # IMU configuration - be more selective about what to use
    imu0: /imu/data
    imu0_config: [false, false, false,  # position off
                  false, false, false,  # orientation off (no magnetometer)
                  false, false, false,  # linear velocities off
                  false, false, true,   # angular velocities (only Z-axis for yaw rate)
                  true, true, false]    # linear acceleration (X,Y only, not Z due to gravity)
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true  # Important for upside-down IMU
    
    # More conservative IMU covariances
    imu0_linear_acceleration_covariance_override: [0.5, 0.0, 0.0,
                                                   0.0, 0.5, 0.0,
                                                   0.0, 0.0, 1e6]  # Moderate trust in X,Y accel
    imu0_angular_velocity_covariance_override: [1e6, 0.0, 0.0,
                                                0.0, 1e6, 0.0,
                                                0.0, 0.0, 0.1]   # Only trust Z angular velocity

    # Process noise - describes how much the robot state can change between updates
    process_noise_covariance: [0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6]
