ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Odometry from encoders with better covariance values
    odom0: /wheel/odom
    odom0_config: [true, true, false,   # x, y position
                   false, false, true,  # roll, pitch, yaw -> yaw enabled
                   true, true, false,   # vx, vy linear velocity
                   false, false, true,  # angular velocities -> vz enabled
                   false, false, false] # accel -> off
    odom0_differential: false
    odom0_relative: false
    # Lower process noise for wheel odometry (more trust in encoders)
    odom0_pose_covariance_override: [1e-2, 0.0, 0.0, 0.0, 0.0, 0.0,
                                    0.0, 1e-2, 0.0, 0.0, 0.0, 0.0,
                                    0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
                                    0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
                                    0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
                                    0.0, 0.0, 0.0, 0.0, 0.0, 1e-1]
    odom0_twist_covariance_override: [1e-2, 0.0, 0.0, 0.0, 0.0, 0.0,
                                     0.0, 1e-2, 0.0, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 1e6, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 1e6, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 0.0, 1e6, 0.0,
                                     0.0, 0.0, 0.0, 0.0, 0.0, 1e-2]

    # IMU (gyro and accel) with adjusted covariance
    imu0: /imu/data
    imu0_config: [false, false, false,  # position -> off
                  false, false, false,  # orientation -> off (no magnetometer)
                  false, false, false,  # linear velocities -> off
                  true, true, true,     # angular velocities -> all enabled
                  true, true, false]    # linear accel x,y -> z disabled (gravity)
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    # Higher noise for IMU (less trust, use for corrections only)
    imu0_linear_acceleration_covariance_override: [1e-1, 0.0, 0.0,
                                                  0.0, 1e-1, 0.0,
                                                  0.0, 0.0, 1e6]
    imu0_angular_velocity_covariance_override: [1e-2, 0.0, 0.0,
                                               0.0, 1e-2, 0.0,
                                               0.0, 0.0, 1e-2]

    # Process noise (how much we trust the motion model)
    process_noise_covariance: [1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 1e-2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6, 0.0, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-2, 0.0, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-3, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e6]
